//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodesStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Api.Resources.Resources.CodesStrings", typeof(CodesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audience.
        /// </summary>
        public static string AppSettingsAudienceSectionName {
            get {
                return ResourceManager.GetString("AppSettingsAudienceSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secret.
        /// </summary>
        public static string AppSettingsAudienceSectionSecretName {
            get {
                return ResourceManager.GetString("AppSettingsAudienceSectionSecretName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a $$body$$.
        /// </summary>
        public static string BaseEmailTemplateBodyToken {
            get {
                return ResourceManager.GetString("BaseEmailTemplateBodyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ./Resources/BaseEmailTemplate/BaseTemplate.html.
        /// </summary>
        public static string BaseEmailTemplateFile {
            get {
                return ResourceManager.GetString("BaseEmailTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a $$title$$.
        /// </summary>
        public static string BaseEmailTemplateTitleToken {
            get {
                return ResourceManager.GetString("BaseEmailTemplateTitleToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Note -.
        /// </summary>
        public static string CartEmailFilePrefix {
            get {
                return ResourceManager.GetString("CartEmailFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cart Delivery Note.
        /// </summary>
        public static string CartEmailSubjec {
            get {
                return ResourceManager.GetString("CartEmailSubjec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a csv.
        /// </summary>
        public static string CsvMediaSubType {
            get {
                return ResourceManager.GetString("CsvMediaSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a text.
        /// </summary>
        public static string CsvMediaType {
            get {
                return ResourceManager.GetString("CsvMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy HH:mm.
        /// </summary>
        public static string DateTimeFormat_DD_MM_YYYY_HH_mm {
            get {
                return ResourceManager.GetString("DateTimeFormat_DD_MM_YYYY_HH_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ./Resources/DeliveryNoteEmailTemlate/DeliberyNoteTemplate.html.
        /// </summary>
        public static string DeliveryNoteEmailTemplateFile {
            get {
                return ResourceManager.GetString("DeliveryNoteEmailTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Author.
        /// </summary>
        public static string DeliveryNoteFileAuthorHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileAuthorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cart Description:;.
        /// </summary>
        public static string DeliveryNoteFileCartDescriptionHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileCartDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Date;.
        /// </summary>
        public static string DeliveryNoteFileCloseDateHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileCloseDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation Date;.
        /// </summary>
        public static string DeliveryNoteFileCreationDateHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileCreationDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User:;.
        /// </summary>
        public static string DeliveryNoteFileCreationUserHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileCreationUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery Note Date;.
        /// </summary>
        public static string DeliveryNoteFileDeliveryNoteDateHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileDeliveryNoteDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code;.
        /// </summary>
        public static string DeliveryNoteFileItemCodeHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileItemCodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item;.
        /// </summary>
        public static string DeliveryNoteFileItemHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motive:;.
        /// </summary>
        public static string DeliveryNoteFileMotiveHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileMotiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity;.
        /// </summary>
        public static string DeliveryNoteFileQuantityHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileQuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referer:;.
        /// </summary>
        public static string DeliveryNoteFileRefererHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileRefererHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work Order:;.
        /// </summary>
        public static string DeliveryNoteFileWorkOrderHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteFileWorkOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date;.
        /// </summary>
        public static string DeliveryNoteStatusDateHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteStatusDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status Name;.
        /// </summary>
        public static string DeliveryNoteStatusNameHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteStatusNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations;.
        /// </summary>
        public static string DeliveryNoteStatusObservationsHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteStatusObservationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User;.
        /// </summary>
        public static string DeliveryNoteStatusUserNameHeader {
            get {
                return ResourceManager.GetString("DeliveryNoteStatusUserNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;&lt;td&gt;{0}&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string DeliveryNoteTemplateItemRow {
            get {
                return ResourceManager.GetString("DeliveryNoteTemplateItemRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a $$items$$.
        /// </summary>
        public static string DeliveryNoteTemplateItemsToken {
            get {
                return ResourceManager.GetString("DeliveryNoteTemplateItemsToken", resourceCulture);
            }
        }
    }
}
