//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CartWeb.Kiosco.Api.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A {0} cart can´t be {1}.
        /// </summary>
        public static string A0CartCantBe1 {
            get {
                return ResourceManager.GetString("A0CartCantBe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMTP service failed. Check configuration..
        /// </summary>
        public static string ErrorSMTP {
            get {
                return ResourceManager.GetString("ErrorSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The last status of the cart is different from Open.
        /// </summary>
        public static string LastStatusCartDifferentToOpen {
            get {
                return ResourceManager.GetString("LastStatusCartDifferentToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User {0} has logged in for the first time. .
        /// </summary>
        public static string NotificationFirstLoginMessage {
            get {
                return ResourceManager.GetString("NotificationFirstLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Notification] User {0} - First login..
        /// </summary>
        public static string NotificationFirstLoginSubject {
            get {
                return ResourceManager.GetString("NotificationFirstLoginSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product {0} - {1} was loaded manually, please check the barcode..
        /// </summary>
        public static string NotificationReportProductMessage {
            get {
                return ResourceManager.GetString("NotificationReportProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Report] Product {0} - {1} .
        /// </summary>
        public static string NotificationReportProductSubject {
            get {
                return ResourceManager.GetString("NotificationReportProductSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email was sent at.
        /// </summary>
        public static string TestEmailMessage {
            get {
                return ResourceManager.GetString("TestEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Test] Test Mail - Optimus.
        /// </summary>
        public static string TestEmailSubject {
            get {
                return ResourceManager.GetString("TestEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is an open cart for the user.
        /// </summary>
        public static string ThereIsAnOpenCartForTheUser {
            get {
                return ResourceManager.GetString("ThereIsAnOpenCartForTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no cart with this Id.
        /// </summary>
        public static string ThereIsNoCartWithThisId {
            get {
                return ResourceManager.GetString("ThereIsNoCartWithThisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ThereIsNoProductWithThisBarcode.
        /// </summary>
        public static string ThereIsNoProductWithThisBarcode {
            get {
                return ResourceManager.GetString("ThereIsNoProductWithThisBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not enabled..
        /// </summary>
        public static string UnauthorizedUserNotEnabled {
            get {
                return ResourceManager.GetString("UnauthorizedUserNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User or Password incorrect.
        /// </summary>
        public static string UnauthorizedUserOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UnauthorizedUserOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User does not have the appropriate profile.
        /// </summary>
        public static string UnauthorizedUserWithContentProfileIncorrect {
            get {
                return ResourceManager.GetString("UnauthorizedUserWithContentProfileIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User without profile.
        /// </summary>
        public static string UnauthorizedUserWithoutContentProfile {
            get {
                return ResourceManager.GetString("UnauthorizedUserWithoutContentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserWithoutCostCenter.
        /// </summary>
        public static string UserWithoutCostCenter {
            get {
                return ResourceManager.GetString("UserWithoutCostCenter", resourceCulture);
            }
        }
    }
}
